TextEditorServer/EditorApp/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
	url(r'^createUser/$', views.createUser, name='createUser'),
	url(r'^logout/$', views.logoutUser, name='logout'),
	url(r'^upload/$', views.upload, name='upload'),
	url(r'^download/$', views.download, name='download'),
)

TextEditorServer/TextEditorServer/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
    url("", include("django_socketio.urls")),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
	url(r'^login/$', auth_views.login),
	url("", include("EditorApp.urls")),
)

TextEditorServer/EditorApp/models.py
import mongoengine

class Document(mongoengine.Document):
	id = mongoengine.fields.ObjectIdField(db_field='_id')
	name = mongoengine.fields.StringField(required=True)
	last_change = mongoengine.fields.DateTimeField()
	text = mongoengine.fields.StringField()
	priv = mongoengine.fields.BooleanField()

TextEditorServer/EditorApp/forms.py
from mongoengine.django.auth import User
from django import forms

class UserForm(forms.Form):
	username = forms.CharField(max_length=254)
	password = forms.CharField(label=("Password"), widget=forms.PasswordInput)
	error = ''

	def __init__(self, request=None):
		if request == None:
			forms.Form.__init__(self)
		else:
			self.username = request["username"] 
			self.password = request["password"]

	def is_valid(self):
		if len(User.objects(username = self.username)) != 0:
			self.error = 'User exists'
			return False
		elif len(self.username) == 0 or len(self.password) == 0:
			self.error = 'Invalid username or password, can not be empty'
			return False
		else:
			return True

class FileForm(forms.Form):
	docfile = forms.FileField(
		label='Select a file'
	)
	error = ''

TextEditorServer/EditorApp/views.py
from forms import UserForm, FileForm
from django.http import HttpResponseRedirect, StreamingHttpResponse
from django.shortcuts import render
from mongoengine.django.auth import User
from django.contrib.auth import logout
import logging
import subprocess
import io
import os
from db_manager import create_document
import xhtml2pdf.pisa as pisa
from mongoengine.django.shortcuts import get_document_or_404
from models import Document

try:
    import StringIO
    StringIO = StringIO.StringIO
except Exception:
    from io import StringIO

logger = logging.getLogger('views')

def createUser(request):
    logger.debug(request.POST)
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.create_user(form.username, form.password)
            return HttpResponseRedirect('/')
        else:
            return render(request, 'registration/createUser.html', {'form': UserForm(), 'error': form.error}) 
    else:
        form = UserForm() 

    return render(request, 'registration/createUser.html', {'form': form}) 

def logoutUser(request):
    logout(request)
    return HttpResponseRedirect("/") 

def saveFile(file_struct):
    file_name = file_struct._name
    with io.open('EditorApp/static/media/' + file_name, 'wb') as file:
        logger.info('Saving file ' + file_name)
        file.write(file_struct.file.getvalue())
    return file_name

def upload(request):
    # Handle file upload
    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES)
        if form.is_valid():
            logger.debug('File with type ' + request.FILES['docfile'].content_type + ' uploaded.')
            if request.FILES['docfile'].content_type ==  u'application/vnd.oasis.opendocument.text':
                file_name = saveFile(request.FILES['docfile'])
                logger.info('Converting file ' + file_name)
                content = subprocess.check_output(['OdtConverter/odt2html', '-x', 'OdtConverter/odt2html.xsl', 'EditorApp/static/media/' + file_name])
                logger.info('Deleting file ' + file_name)
                os.remove('EditorApp/static/media/' + file_name)
                logger.info('Saving imported document ' + file_name)
                create_document(None, file_name, content)
            elif request.FILES['docfile'].content_type[:5] == u'image':
                saveFile(request.FILES['docfile'])
            else:
                form = FileForm()
                form.error = 'Invalid type of document.'
                logger.error('Wrong type of document.')
                return render(request, 'upload.html', {'form': form})
            # Redirect to the document list after POST
            return HttpResponseRedirect('/')
    else:
        form = FileForm() # A empty, unbound form
    return render(request, 'upload.html', {'form': form})

def get_user_permissions(request):
    user_permissions = []
    if not request.user.is_anonymous():
        for permission in request.user.user_permissions:
            user_permissions.append(permission._DBRef__id)
    return user_permissions

def download(request):
    if request.method == 'GET':
        document = get_document_or_404(Document, id = request.GET.get('documentId'))
        if document.priv == False or document.id in get_user_permissions(request):
            logger.debug('Exporting ' + document.name)
            result = StringIO()
            pdf = pisa.CreatePDF(StringIO(document.text.replace('<img src=\"/static', '<img src=\"EditorApp/static')), result)
            if not pdf.err:
                response = StreamingHttpResponse(result.getvalue(), content_type='application/pdf')
                response['Content-Disposition'] = 'attachment;filename=' + document.name.replace(' ', '_') + '.pdf'
                logger.debug('Document ' + document.name + ' was exported successfully')
                return response 
            logger.debug('Failed in export document ' + document.name)
    return HttpResponseRedirect('/')

TextEditorServer/EditorApp/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Web Text Editor</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<meta name="description" content="" />
	<meta name="copyright" content="" />
	<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}KS/css/kickstart.css" media="all" />
	<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}KS/style.css" media="all" />    
	<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/style.css">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}KS/js/kickstart.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/offline.js"></script>
	<script type="text/javascript" charset="utf-8">
		var socket;
		var documentId = undefined;
		var offlineMode = false;
		var noDocumentReplace = false;
		var editorDocument;
		var editorBody;
		var editorIframe;
		var bodyBeforeOperation;
	</script>
	<script type="text/javascript" src="{{STATIC_URL}}js/onlineStatusChecker.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/formatter.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/utils.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/editor.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/rangy-core.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/rangy-selectionsaverestore.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/messageHandler.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/jquery-migrate-1.2.1.min.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/jquery.reveal.js"></script>

	<!-- Google API integration. -->
	<script type="text/javascript" src="{{STATIC_URL}}js/gdrive.js"></script>
	<script type="text/javascript" src="https://apis.google.com/js/client.js?onload=handleClientLoad"></script>

	<!-- Local storage lib -->
	<script type="text/javascript" src="{{STATIC_URL}}js/simpleStorage.js"></script> 

	<style type="text/css">
		body { font-family: "HelveticaNeue","Helvetica-Neue", "Helvetica", "Arial", sans-serif; }
		.big-link { display:block; margin-top: 100px; text-align: center; font-size: 70px; color: #06f; }
	</style>

	{% load socketio_tags %}
	{% socketio %}

</head>
<body>
	<!-- Menu Horizontal -->
	<ul id="menu" class="menu">
		<li><a><span class="icon"></span>File</a>
			<ul>
				<li><a id="newDocumentMenu" href="#" onclick="newDocAtStart()"><i class="fa fa-file-text-o"></i> New document</a></li>
				<li><a id="import" href="upload"><i class="fa fa-upload"></i> Import</a></li>
				<li><a id="export" href="#"><i class="fa fa-file-pdf-o"></i> Export to PDF</a></li>
				<li><a href="#" id="fileUpload" data-reveal-id="fileUploadModal" data-animation="fadeAndPop"><i class="fa fa-upload"></i> Upload image</a></li>
				<li><a id="documentListButton" href="#" data-reveal-id="fileListModal" data-animation="fadeAndPop">
				<i class="fa fa-list-alt"></i> Documents list</a></li>
			</ul>
		</li>
		<li><a id='accounts'><span class="icon"></span>Accounts</a>
			<ul>
				<li><a href="createUser/"><i class="fa fa-user-plus"></i> Create</a></li>
				<li><a id='logout' href="logout/"><i class="fa fa-sign-out"></i> Logout</a></li>
			</ul>
		</li>
		<li><a id='gDriveIntegration'><span class="icon"></span>Google Drive</a>
			<ul>
				<li id="authorizeGDrive">
					<a id="authorizeGDriveLink" href="#"> Authorize with GoogleDrive</a>
				</li>
				<li id="exploreGDrive" class="authorizedMethods">
					<a id="exploreGDriveLink" href="#"> Explore GoogleDrive</a>
				</li>
				<li id="saveGDrive" class="authorizedMethods">
					<a id="saveGDriveLink" href="#"> Save document on GoogleDrive</a>
				</li>
			</ul>
		</li>
		<li class="right"> 
			{% if user.is_authenticated %}
			    <p>Welcome, {{ user }}. </p>
			{% else %}
				<a href="{% url 'django.contrib.auth.views.login' %}"><i class="fa fa-sign-in"></i> Login</a>
			{% endif %}
		</li>
	</ul>

	<li>
		<div class="page-header">
			<h3 id="documentNameHeader">Document Name</h3>
		</div>
	</li>
	
	
	
	<ul id='buttonBar' class="button-bar">
		<li><a id="newDocument" data-reveal-id="fileNameModal" data-animation="fadeAndPop"><i class="fa fa-file-text-o"></i></a></li>
		<li><a id="saveDocument" data-reveal-id="fileNameModal" data-animation="fadeAndPop"><i class="fa fa-floppy-o"></i></a></li>
		<li><a id="boldText"><i class="fa fa-bold"></i></a></li>
		<li><a id="italicText"><i class="fa fa-italic"></i> </a></li>
		<li><a id="underlineText"><i class="fa fa-underline"></i> </a></li>
		<li><a id="list"><i class="fa fa-list-ul"></i> </a></li>
		<li><a id="alignLeft"><i class="fa fa-align-left"></i></a></li>
		<li><a id="alignRight"><i class="fa fa-align-right"></i></a></li>
		<li><a id="alignCenter"><i class="fa fa-align-center"></i></a></li>
		<li><a id="localSave" style="display: none;"><i class="fa fa-floppy-o"></i> Local Save</a></li>
		<li ><a href="#"  data-reveal-id="linkUploadModal" data-animation="fadeAndPop" id="image"  ><i class="fa fa-picture-o"></i></a></li>
		<li><a id="emoticons" onclick="insertAtCaret('emotikon.jpeg', '{{STATIC_URL}}' + 'img/' )"><i class="fa fa-smile-o"></i></a></li>
		<li><label for="fontSize">Select font size</label>
			<select id="fontSize" onchange="changeFontSize();">
			<option value="0" selected = "true">Font size</option>
			<option value="1">1</option>
			<option value="2">2</option>
			<option value="3">3</option>
			<option value="6">6</option>
			<option value="8">8</option>
			<option value="12">12</option>
			<option value="16">16</option>
			<option value="24">24</option>
			<option value="48">48</option>
			<option value="72">72</option>
			</select></li>
	</ul>
	<br/>
	<div>
		<iframe id="editorContent" name="editorContent" src="{{STATIC_URL}}html/textbox.html" frameborder="0" >
		</iframe>
	</div>
	<div id="fileListModal" class="reveal-modal">
		<h3>Select file from list</h3>
		<table class="sortable" cellspacing="0" cellpadding="0">
			<thead>
				<tr>
					<th>File name</th>
				</tr>
			</thead>
			<tbody id="documentList">
			</tbody>
		</table>
	    <a id="showFileListTrigger" data-reveal-id="fileListModal" data-closeonbackgroundclick="false"></a>
	</div>
	<div id="waitPageModal" class="reveal-modal">
	     <h1>Loading page</h1>
	     <p>Please wait...</p>
	     <a id="closeWaitPageTrigger" class="close-reveal-modal"></a>
	     <a id="showWaitPageTrigger" data-reveal-id="waitPageModal" data-closeonbackgroundclick="false"></a>
	</div>
	<div id="fileNameModal" class="reveal-modal">
		<label for="documentName">Document name:</label>
		<input id="documentName" type="text" />
		<button id="saveDocumentButton" class="medium green">Save</button>
		<button class="medium" onclick="$('#fileNameModal').trigger('reveal:close');">Cancel</button>
		<input type="checkbox" id="privateFlag">Private document</input>
		<a id="closeFileNameTrigger" class="close-reveal-modal"></a>
		<a id="showFileNameModalTrigger" data-reveal-id="fileNameModal"></a>
	</div>
	<div id="fileNameModalAtStart" class="reveal-modal">
		<label for="documentName">Document name:</label>
		<input id="documentNameAtStart" type="text" />
		<button id="saveDocumentButtonAtStart" class="medium green">Save</button>
		<button class="medium" onclick="swapWindows()">Cancel</button>
		<input type="checkbox" id="privateFlagAtStart">Private document</input>
		<a id="showFileNameModalAtStartTrigger" data-reveal-id="fileNameModalAtStart" data-closeonbackgroundclick="false"></a>
	</div>
	<div id="saveGDriveWindow" class="reveal-modal">
		<label for="documentName">Document name:</label>
		<input id="gDriveDocName" type="text" />
		<button id="saveGDriveDocButton" class="medium green">Save</button>
		<button class="medium" onclick="$('#saveGDriveWindow').trigger('reveal:close');">Cancel</button>
		<a id="saveGDriveWindowTrigger" data-reveal-id="saveGDriveWindow"></a>
	</div>
	<div id="fileUploadModal" class="reveal-modal">
		<label>Upload file:</label>
		<div id="dropzone">
			<form action="{% url "upload" %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				 <input id="id_docfile" name="docfile" type="file" />
				 <button class="medium"  name="press" value="Upload" type="submit" onclick="insertImage('{{STATIC_URL}}media/')">Submit</button>
			</form>
		</div>
	</div>

	<div id="linkUploadModal" class="reveal-modal">
		<label>Enter link:</label>
		<input id="linkInputValue" type="text" />
		<button id="linkSubmitButton" class="medium green">Submit</button>
		<button class="medium" onclick="$('#linkUploadModal').trigger('reveal:close');">Cancel</button>
		<a id="linkUploadModalTrigger" class="close-reveal-modal"></a>
	</div>
	
	
</body>
</html>

TextEditorServer/EditorApp/templates/upload.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Upload document</title>	
		<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/login.css">
	</head>
	<body>
		<div class="greenElements">
	  		<h1>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</h1>
			<form action="{% url "upload" %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<p style="color:red">{{ form.error }}</p>
				<p>
					{{ form.docfile.errors }}
					{{ form.docfile }}
				</p>
				<br/>
				<p><input type="submit" name="press" value="Upload" /></p>
			</form>
		</div>
	</body>
</html>